
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.test
{
public partial class TbFirst
{
    private readonly System.Collections.Generic.Dictionary<string, test.MyFirstTable> _dataMap;
    private readonly System.Collections.Generic.List<test.MyFirstTable> _dataList;
    
    public TbFirst(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, test.MyFirstTable>(n);
        _dataList = new System.Collections.Generic.List<test.MyFirstTable>(n);
        for(int i = n ; i > 0 ; --i)
        {
            test.MyFirstTable _v;
            _v = global::cfg.test.MyFirstTable.DeserializeMyFirstTable(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, test.MyFirstTable> DataMap => _dataMap;
    public System.Collections.Generic.List<test.MyFirstTable> DataList => _dataList;

    public test.MyFirstTable GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public test.MyFirstTable Get(string key) => _dataMap[key];
    public test.MyFirstTable this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

