
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.test
{
public partial class TbSecond
{
    private readonly System.Collections.Generic.Dictionary<string, test.MySecondTable> _dataMap;
    private readonly System.Collections.Generic.List<test.MySecondTable> _dataList;
    
    public TbSecond(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, test.MySecondTable>(n);
        _dataList = new System.Collections.Generic.List<test.MySecondTable>(n);
        for(int i = n ; i > 0 ; --i)
        {
            test.MySecondTable _v;
            _v = global::cfg.test.MySecondTable.DeserializeMySecondTable(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, test.MySecondTable> DataMap => _dataMap;
    public System.Collections.Generic.List<test.MySecondTable> DataList => _dataList;

    public test.MySecondTable GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public test.MySecondTable Get(string key) => _dataMap[key];
    public test.MySecondTable this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

