//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由DecoratorRegistryGenerator自动生成，请勿手动修改
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MOYV.RunTime.Game.Logic
{
    /// <summary>
    /// 功能装饰器静态注册表
    /// 此文件由工具自动生成，包含了所有已注册的 FuncDecoratorBase 派生类
    /// </summary>
    public sealed partial class FuncDecoratorStaticRegistry
    {
        /// <summary>
        /// 功能类型到注册信息的静态映射
        /// 元组包含: (装饰器类型, 命令偏移量, 排序值)
        /// </summary>
        private static readonly Dictionary<AFuncType, (Type type, int offset, int order)> Func2Registries = new()
        {
            [AFuncType.test] = (typeof(AFunc_Test), 10, 1),
            [AFuncType.testE] = (typeof(AFunc_TestE), 100, 1),
            [AFuncType.Trigger] = (typeof(AFunc_Trigger), 10, 2)
        };

        /// <summary>
        /// 装饰器类型到注册信息的静态映射
        /// 元组包含: (功能类型, 命令偏移量, 排序值)
        /// </summary>
        private static readonly Dictionary<Type, (AFuncType funcType, int offset, int order)> Type2Registries = new()
        {
            [typeof(AFunc_Test)] = (AFuncType.test, 10, 1),
            [typeof(AFunc_TestE)] = (AFuncType.testE, 100, 1),
            [typeof(AFunc_Trigger)] = (AFuncType.Trigger, 10, 2)
        };

    }
}
