using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using System.Linq;

using UnityEngine;
using UnityEditor;
using UnityEditor.Callbacks;
using MOYV.RunTime.Game.Logic;
using MOYV.RunTime.Game.Tool;


namespace MOYV.Game.Editor
{
    /// <summary>
    /// 功能装饰器静态注册表生成器
    /// 在代码编译完成后自动生成静态映射文件
    /// </summary>
    [InitializeOnLoad]
    public class DecoratorRegistryGenerator
    {
        private const string GENERATED_FILE_PATH = "Assets/Game/Scripts/Game/Runtime/Logic/Decorate/FuncDecoratorStaticRegistry_Gen.cs";

        [MenuItem("Tools/功能装饰器/手动生成静态注册表")]
        public static void ManuallyGenRegistry() => GenerateStaticRegistry();
        
                [DidReloadScripts]
        public static void GenerateStaticRegistry()
        {
            try
            {
                string newContent = GenerateFileContent(CollectRegistryInfo());
                if (File.Exists(GENERATED_FILE_PATH))
                {
                    string existingContent = File.ReadAllText(GENERATED_FILE_PATH);
                    if (existingContent == newContent)
                    {
                        // 内容没有变化，不需要写入
                        return;
                    }
                }

                // 写入文件
                File.WriteAllText(GENERATED_FILE_PATH, newContent);
                AssetDatabase.Refresh(); // 这会触发重新编译
            }
            catch (Exception ex)
            {
                Debug.LogError($"❌ 生成静态注册表失败: {ex.Message}");
            }
        }

        const string LogicNameSpace = "MOYV.RunTime.Game.Logic";

        /// <summary>
        /// 收集所有通过 FuncDecoratorAttribute 注册的类型信息
        /// </summary>
        private static List<RegistryEntry> CollectRegistryInfo()
        {
            var entries = new List<RegistryEntry>();
            var baseType = typeof(AFuncDecorate);

            // 扫描所有程序集
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                TryCollectAssembly(assembly, entries, baseType);
            }

            // 去重
            var duplicateMap = new Dictionary<AFuncType, Type>();
            foreach (var entry in entries)
            {
                if (duplicateMap.TryGetValue(entry.FuncType, out var type))
                {
                    MDebug.Error($"【前端同学】{entry.Type.Name}注册的FuncType: {entry.FuncType}与{type.Name}冲突，请检查。");
                    continue;
                }
                duplicateMap.Add(entry.FuncType, entry.Type);
            }
            entries = entries.Where(x => duplicateMap.Values.Contains(x.Type)).ToList();

            // 按 FuncType 排序
            entries.Sort((a, b) => a.FuncType.CompareTo(b.FuncType));

            return entries;
        }

        private static void TryCollectAssembly(Assembly assembly, List<RegistryEntry> entries, Type baseType)
        {
            var aFullName = assembly.FullName;
            if (aFullName.Contains("Editor") || !(aFullName.StartsWith(LogicNameSpace) || aFullName.StartsWith("Assembly-CSharp")))
            {
                return;
            }

            try
            {
                foreach (var type in assembly.GetTypes())
                {
                    if (type.IsAbstract || !baseType.IsAssignableFrom(type))
                        continue;

                    var attribute = type.GetCustomAttribute<FuncDecoratorAttribute>();
                    if (attribute != null)
                    {
                        entries.Add(new RegistryEntry
                        {
                            FuncType = attribute.FuncType,
                            CmdOffset = attribute.CmdOffset,
                            Type = type,
                            Order = attribute.Order
                        });
                    }
                }
            }
            catch (Exception ex)
            {
                Debug.LogWarning($"扫描程序集 {assembly.GetName().Name} 时出错: {ex.Message}");
            }
        }

        /// <summary>
        /// 生成静态文件内容
        /// </summary>
        private static string GenerateFileContent(List<RegistryEntry> entries)
        {
            var sb = new StringBuilder();

            // 文件头部
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     此代码由DecoratorRegistryGenerator自动生成，请勿手动修改");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine($"namespace {LogicNameSpace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 功能装饰器静态注册表");
            sb.AppendLine("    /// 此文件由工具自动生成，包含了所有已注册的 FuncDecoratorBase 派生类");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public sealed partial class FuncDecoratorStaticRegistry");
            sb.AppendLine("    {");

            // 生成功能类型到注册信息的映射字典
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 功能类型到注册信息的静态映射");
            sb.AppendLine("        /// 元组包含: (装饰器类型, 命令偏移量, 排序值)");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        private static readonly Dictionary<AFuncType, (Type type, int offset, int order)> Func2Registries = new()");
            sb.AppendLine("        {");

            for (int i = 0; i < entries.Count; i++)
            {
                var entry = entries[i];
                var comma = i < entries.Count - 1 ? "," : "";
                sb.AppendLine($"            [AFuncType.{entry.FuncType}] = (typeof({entry.Type.Name}), {(int)entry.CmdOffset}, {entry.Order}){comma}");
            }

            sb.AppendLine("        };");
            sb.AppendLine();

            // 生成类型到注册信息的映射字典
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 装饰器类型到注册信息的静态映射");
            sb.AppendLine("        /// 元组包含: (功能类型, 命令偏移量, 排序值)");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        private static readonly Dictionary<Type, (AFuncType funcType, int offset, int order)> Type2Registries = new()");
            sb.AppendLine("        {");

            for (int i = 0; i < entries.Count; i++)
            {
                var entry = entries[i];
                var comma = i < entries.Count - 1 ? "," : "";
                sb.AppendLine($"            [typeof({entry.Type.Name})] = (AFuncType.{entry.FuncType}, {(int)entry.CmdOffset}, {entry.Order}){comma}");
            }

            sb.AppendLine("        };");
            sb.AppendLine();

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// 注册条目信息
        /// </summary>
        private class RegistryEntry
        {
            public AFuncType FuncType { get; set; }
            public AFuncCMDOffset CmdOffset { get; set; }
            public Type Type { get; set; }
            public int Order { get; set; }
        }
    }
}