
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public test.TbFirst TbFirst {get; }
    public test.TbSecond TbSecond {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbFirst = new test.TbFirst(loader("test_tbfirst"));
        TbSecond = new test.TbSecond(loader("test_tbsecond"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbFirst.ResolveRef(this);
        TbSecond.ResolveRef(this);
    }
}

}
